#spring:
#  application:
#    name: SVC-GATEWAY
#  config:
#    import: configserver:${URL_CONFIG_SERVER}
#  cloud:
#    config:
#      profile: ${ACTIVE_PROFILE}

server:
  port: 7070

# CONFIGURAÇÕES GATEWAY
spring:
  application:
    name: SVC-GATEWAY
#  config:
#    import: configserver:${URL_CONFIG_SERVER}
#  cloud:
#    config:
#      profile: ${ACTIVE_PROFILE}
    gateway:
      actuator:
        verbose:
          enabled: true
      metrics:
        enabled: true
    discovery:
      enabled: true

# CONFIGURAÇÕES EUREKA
#eureka:
#  client:
#    fetch-register: true
#    register-with-eureka: true
#    defaultZone: http://fnp-svc-discovery-server-8c7614af535c.herokuapp.com/eureka
#  serviceUrl:
#    defaultZone: http://fnp-svc-discovery-server-8c7614af535c.herokuapp.com/eureka
#  instance:
#  instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  prefer-ip-address: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000}/eureka/

# CONFIGURAÇÕES ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
          - 'gateway'
  endpoint:
    gateway:
      enabled:
        true